version: "3.7"
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd2022"
      MSSQL_PID: "Express"
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-Slocalhost",
          "-Usa",
          "-P${SA_PASSWORD}",
          "-Q",
          "CREATE DATABASE [JustPlay]",
        ]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 3
    ports:
      - "1433:1433"
    networks:
      - backend
  justplaybackend:
    build: ./backend
    image: testbackendimage
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "8080:80"
    depends_on:
      ms-sql-server:
        condition: service_healthy
    networks:
      - backend
  justplayfrontend:
    build: ./frontend
    image: albertolucchesi/frontendreact
    ports:
      - "3000:3000"
    depends_on:
      - justplaybackend
    networks:
      - backend
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
