INSERT INTO videogames_owned(user_email, videogame_id)
VALUES ('test@test.com', '1')
INSERT INTO videogames_owned(user_email, videogame_id)
VALUES ('test@test.com', '2')
INSERT INTO videogames_owned(user_email, videogame_id)
VALUES ('test@test.com', '3')
INSERT INTO videogames_owned(user_email, videogame_id)
VALUES ('test@test.com', '4')
INSERT INTO videogames_owned(user_email, videogame_id)
VALUES ('test@test.com', '5')
INSERT INTO videogames_owned(user_email, videogame_id)
VALUES ('test@test.com', '6')
INSERT INTO videogames_owned(user_email, videogame_id)
VALUES ('test@test.com', '7')

INSERT INTO videogames_wishlist(user_email, videogame_id)
VALUES ('test@test.com', '10')
INSERT INTO videogames_wishlist(user_email, videogame_id)
VALUES ('test@test.com', '11')
INSERT INTO videogames_wishlist(user_email, videogame_id)
VALUES ('test@test.com', '12')
INSERT INTO videogames_wishlist(user_email, videogame_id)
VALUES ('test@test.com', '13')
INSERT INTO videogames_wishlist(user_email, videogame_id)
VALUES ('test@test.com', '14')